version: '3.9'

networks:
    external:
        external: true

services:
    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - 80:80
        networks:
            - external
        volumes:
            - /home/core/personal_site/_site:/usr/share/nginx/html

